### ISSUE TITLE
One small error noticed!

### ISSUE THREAD

**Issue by rasputin303** [smarthall/python-lifx-sdk#1]
In line 415:

```Python
payload_size = frame_address_struct.size - payload_start
```

Should be:

```Python
payload_size = frame_header_struct.size - payload_start
```

Otherwise it crashes if you try to parse a message type that isn't in the messages dictionary.

**Comment by smarthall** [comment]
Thanks! Fixed in 32ea5597e1e0d79e042c94d40946374a357af30d
